import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Explore-Next-js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between bg-red-900 text-white p-5">
          <h1>Explore Next Js</h1>
          <ul className="flex gap-5 ">
            <li>Home</li>
            <li>Blog</li>
            <li>Service</li>
            <li>Contact</li>
            <li>About</li>
          </ul>
        </nav>
        <div className="h-screen">
          {children}
        </div>
        <footer className="footer footer-center bg-base-300 text-base-content p-4 w-full bg-red-900 text-center text-white">
          <aside>
            <p>Copyright © {new Date().getFullYear()} - All right reserved by ACME Industries Ltd</p>
          </aside>
        </footer>
      </body>
    </html >
  );
}
